### ISSUE TITLE
OC doesnt work with projects any more

### ISSUE THREAD

**Issue by astolzen** [openshift/microshift#1008]
#### What happened?
Created a Microshift RPM from the source following (https://github.com/openshift/microshift/blob/main/docs/devenv_rhel8.md)
Build & Installed via RPM: microshift-4.12.0-4.10.0_0.microshift_2022_09_08_132255_166_g69242a85.el8.x86_64.rpm
into a KVM Virtual machine with RHEL 8.6

Started the Instance which seems to work as expected:
```
oc get nodes
NAME                STATUS   ROLES                         AGE     VERSION
dhcp223.mykier.ip   Ready    control-plane,master,worker   2d22h   v1.24.0
```
and 
```
oc get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS    MESSAGE                         ERROR
scheduler            Healthy   ok                              
etcd-0               Healthy   {"health":"true","reason":""}   
controller-manager   Healthy   ok
```
*BUT* I cannot create projects or switch between them with the OC command, which works perfectly on Microshift 1.21 or Openshift 4.10-4.11
```
oc new-project testing123
Error from server (NotFound): the server could not find the requested resource (get projectrequests.project.openshift.io)

oc project default
error: unable to default to a user name: the server could not find the requested resource (get users.user.openshift.io ~)
```
whereas kubectl does work:

```
kubectl create namespace testing123
namespace/testing123 created
kubectl config set-context --current --namespace=testing123
Context "microshift" modified.
```

#### What did you expect to happen?
The oc client should work as it does with Microshift 1.21 or Openshift 4.1x

#### How to reproduce it (as minimally and precisely as possible)?
Build RPM, Install Microshift on RHEL 8.6 or on RHEL for EDGE

#### Environment
- MicroShift version (use `microshift version`):
```
MicroShift Version: 4.10.0-0.microshift-2022-09-08-132255-166-g69242a85
Base OCP Version: 4.12.0-0.nightly-2022-09-25-071630

```
- Hardware configuration:
  KVM virtual Machine (UEFI, Q35, 4vCPU, 8 GB RAM) on Thinpad P1Gen2 
- OS (e.g: `cat /etc/os-release`):
```
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"

```
- Kernel (e.g. `uname -a`):
`Linux dhcp223.mykier.ip 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Sat Aug 27 02:44:20 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Others:

**Comment by dhellmann** [comment]
The project API has been removed from MicroShift along with the other OpenShift APIs that we don't intend to support for those use cases. See https://github.com/openshift/microshift/blob/main/docs/enabled_apis.md for a list of the OpenShift APIs that are included in MicroShift.
