### ISSUE TITLE
In place upgrade 

### ISSUE THREAD

**Issue by debankur1** [openshift/microshift#1138]
For single-node clusters how do we do an In-place upgrade?

**Comment by ggiguash** [comment]
MicroShift is to be distributed as a set of RPM packages. The upgrade amounts to stopping the MicroShift service, updating the RPM packages and starting the service.

**Comment by debankur1** [comment]
okay understood, basically, there will be downtime so the workload will stop for a while and again come back.
what happens if the upgrade fails will it automatically rollback to the previous version?

**Comment by ggiguash** [comment]
Yes, we're planning to make use of Greenboot functionality for automatic rollbacks in case of upgrade failure.
See [Managing RHEL for Edge Images](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/composing_installing_and_managing_rhel_for_edge_images/managing-rhel-for-edge-images_composing-installing-managing-rhel-for-edge-images)

**Comment by debankur1** [comment]
> Yes, we're planning to make use of Greenboot functionality for automatic rollbacks in case of upgrade failure. See [Managing RHEL for Edge Images](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/composing_installing_and_managing_rhel_for_edge_images/managing-rhel-for-edge-images_composing-installing-managing-rhel-for-edge-images)

Many thanks.
