### ISSUE TITLE
[BUG] Microshift fails to start

### ISSUE THREAD

**Issue by jordanpwalsh** [openshift/microshift#1202]
#### What happened?

Attempted to start microshift with `microshift run`

#### What did you expect to happen?

Microshift starts

#### How to reproduce it (as minimally and precisely as possible)?
1. Stopped a boot-looping microshift: systemctl stop microshift
2. Tested disabled selinux
3. as root: microshift run

#### Environment
- MicroShift version (use `microshift version`): MicroShift Version: 4.8.0-0.microshift-2022-04-20-141053
- Hardware configuration: WSL Virtual Machine
- OS (e.g: `cat /etc/os-release`): "Fedora Linux 37 (Thirty Seven)
- Kernel (e.g. `uname -a`):  5.15.79.1-microsoft-standard-WSL2
- Others:

#### Relevant logs 

The rest are attached. 

I1218 09:17:04.197692    1290 openshift-oauth-server.go:112] oauth-apiserver is ready
I1218 09:17:04.197738    1290 manager.go:112] Starting openshift-default-scc-manager
I1218 09:17:04.198234    1290 scc.go:73] Applying scc api assets/scc/0000_20_kube-apiserver-operator_00_scc-anyuid.yaml
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x1c0cbdf]

[out.log](https://github.com/openshift/microshift/files/10253997/out.log)

**Comment by ggiguash** [comment]
@jordanpwalsh, please use the latest software from https://github.com/openshift/microshift.
The 4.8.0 version is rather old and it has problems running on Fedora. 

You can use [Getting Started](https://github.com/openshift/microshift/blob/main/docs/getting_started.md) instructions for an easy onboarding experience.

/close
