### ISSUE TITLE
New pre-built releases?

### ISSUE THREAD

**Issue by christophkreutzer** [openshift/microshift#1206]
Sorry in advance if this is the wrong communication channel.

Is there any plan to build new public releases (based on OKD?) again, and update the docs to match the new releases? Thanks!

**Comment by ggiguash** [comment]
We are hoping to resume upstream activities for MicroShift with OKD sometime next year (see USHIFT-395). This task has the prerequisites of making the current CNI/CSI drivers pluggable to allow their replacement with the appropriate upstream solutions (see USHIFT-599).

**Comment by christophkreutzer** [comment]
Thanks for the swift response! :) It's a bummer it's gonna take a while. But I'll stay tuned.
