### ISSUE TITLE
[BUG] rpc error: code = Unknown desc = invalid policy in "/etc/containers/policy.json": Unknown key "keyPaths" 

### ISSUE THREAD

**Issue by tkagn** [openshift/microshift#1207]
#### What happened?
Deployed microshift and kube-flannel-ds would not run and other pods would report as pending

#### What did you expect to happen? 
All pods to be running. Ability to deploy apps.

#### How to reproduce it (as minimally and precisely as possible)?
1. 'Deploy microshift per docs'
2. 'oc get pods -A'
3.  Notice kube-flannel stuck on container creating and describe of pod reports "invalid policy in "/etc/containers/policy.json": Unknown key "keyPaths""

#### Environment
- MicroShift version (use `microshift version`):
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

MicroShift Version: 4.8.0-0.microshift-2022-04-20-141053
Base OKD Version: 4.8.0-0.okd-2021-10-10-030117

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"

Linux microshift 4.18.0-372.9.1.el8.x86_64 #1 SMP Fri Apr 15 22:12:19 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

Running as KVM VM

**Comment by tkagn** [comment]
Workaround:

edit /etc/containers/policy.json

`{ "default": [ { "type": "insecureAcceptAnything" } ], "transports": { "docker": { "registry.access.redhat.com": [ { "type": "signedBy", "keyType": "GPGKeys", "keyPath": "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release" } ], "registry.redhat.io": [ { "type": "signedBy", "keyType": "GPGKeys", "keyPath": "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release" } ] }, "docker-daemon": { "": [ { "type": "insecureAcceptAnything" } ] } } }`

Change keypaths to keypath 

'"keyPaths": ["/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release", "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta"]' to '"keyPath": "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"'

**Comment by ggiguash** [comment]
@tkagn , thank you for reporting this. 
microshift-4.8.0 is an older version, which we no longer support. Please, use the latest s/w from https://github.com/openshift/microshift. You can experiment with simple [Getting Started](https://github.com/openshift/microshift/blob/main/docs/getting_started.md) instructions to start with.

Also, to avoid the problem you're referring to, please use RHEL 8.7 OS, which contains updated version of CRI-O that does not inhibit this issue.

/close
