### ISSUE TITLE
[BUG] Microshift won't pass - showing dracut-initqueue timeout RHEL 8.7

### ISSUE THREAD

**Issue by vwalek** [openshift/microshift#1217]
#### What happened?

trying to install the microshift on my lab and getting error "dracut-initqueue timeout - starting timeout scripts".
Following guide
https://github.com/openshift/microshift/blob/main/docs/getting_started.md

Just before the dracut timeout the lines are shown.

Tech Preview: NMVe/TCP may not be fully supported.

Using the latest RHEL 8.7 image. Most likely issue with the RHEL.

#### What did you expect to happen?
Normal installation.

#### How to reproduce it (as minimally and precisely as possible)?
1. '...'
2. '...'

#### Environment
- MicroShift version (use `microshift version`):
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`): RHEL 8.7 on Fedora 35
- Kernel (e.g. `uname -a`):  Linux 6.0.12-100.fc35.x86_64

**Comment by ggiguash** [comment]
@vwalek, any special reason for using a 1y-old Fedora 35 as a hypervisor for the MicroShift VM? 
Can you boot a bare RHEL 8.7 DVD ISO?

**Comment by vwalek** [comment]
@ggiguash 

> any special reason for using a 1y-old Fedora 35 as a hypervisor for the MicroShift VM? Can you boot a bare RHEL 8.7 DVD ISO?

@ggiguash I use that version for specific reason. Nevertheless, I tried to run it on Fedora 36 and got the same result. Somehow the RHEL 8.7 won't start in Libvirt.
Any reason why it does so?

**Comment by ggiguash** [comment]
@vwalek, we are using Fedora as development workstation and we have not encountered this issue. Can you provide full boot logs for us to review and see if we can get some answers?

**Comment by vwalek** [comment]
@ggiguash hey, I actually was wrong, my lab was on Fedora 35 too. Upgrading to 36 fixed the issue. Yeah, I would say that the problem is related to the RHEL8 and the Fedora 35. We can close that as not a bug.
