### ISSUE TITLE
[BUG] virt-manager unable to startup "Getting Started with MicroShift" installed VM

### ISSUE THREAD

**Issue by WIP42** [openshift/microshift#1302]
#### What happened?

Background: Built on Fedora-37 set up with nested virtualization enabled on WSL2.
Followed guide: https://github.com/openshift/microshift/blob/main/docs/getting_started.md
After a few minutes, the Microshift system was installed and all services eventually did start up fine.
When host system or WSL is restarted, I am unable to get the corresponding Microshift started again.

Using `sudo virt-manager` I can see `microshift-starter` VM but it is in stopped state.

When starting it, I get errors:
```
Error starting domain: internal error: process exited while connecting to monitor: ERROR cluster 50721 refcount=0 reference=1
ERROR cluster 50722 refcount=0 reference=1
ERROR cluster 50723 refcount=0 reference=1
ERROR cluster 50724 refcount=0 reference=1
ERROR cluster 50725 refcount=0 reference=1
ERROR cluster 50726 refcount=0 reference=1
ERROR cluster 50727 refcount=0 reference=1
ERROR cluster 50728 refcount=0 reference=1
ERROR cluster 50729 refcount=0 reference=1
ERROR cluster 50730 refcount=0 reference=1
ERROR cluster 50731 refcount=0 reference=1
ERROR cluster 50732 refcount=0 reference=1
ERROR cluster 50733 refcount=0 reference=1
ERROR cluster 50734 refcount=0 reference=1
ERROR cluster 50735 refcount=0 reference=1
ERROR cluster 50736 refcount=0 reference=1
ERROR cluster 50737 refcount=0 reference=1
ERROR cluster 50738 refcount=0 reference=1
ERROR cluster 50739 refcount=0 reference=1
ERROR cluster 50740 refcount=0 reference=1
ERROR cluster 50741 refcount=0 reference=1
ERROR cluster 50742 refcount=0 reference=1
ERROR cluster 50743 refcount=0 refere

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1402, in startup
    self._backend.create()
  File "/usr/lib64/python3.11/site-packages/libvirt.py", line 1362, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: process exited while connecting to monitor: ERROR cluster 50721 refcount=0 reference=1
```

#### How to reproduce it (as minimally and precisely as possible)?
1. Follow getting_started.md to install
2. Restart the host system or WSL2
3. Try startup `microshift-starter` via `sudo virt-manager`

#### Environment
- MicroShift version (use `microshift version`):
```
MicroShift Version: 4.12.0-0.microshift-2022-11-17-084702-untagged
Base OCP Version: 4.12.0-0.nightly-2022-11-07-181244
```
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
```
- Kernel (e.g. `uname -a`): Linux microshift-starter.local 4.18.0-425.3.1.el8.x86_64 #1 SMP Fri Sep 30 11:45:06 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by ggiguash** [comment]
@WIP42, can you try installing a base RHEL 8.7 OS without MicroShift? I doubt this issue is caused by adding MicroShift to the image, so I wonder whether we should report it elsewhere?

**Comment by ggiguash** [comment]
@WIP42 , I'm planning to close this issue next week because it's unlikely to be related to MicroShift.
Please, let us know if you have other ideas.

**Comment by WIP42** [comment]
Indeed in WSL2 I could not use the RHEL 8.7 DVD ISO.

After the above problems, I installed via repo instead but found that WSL limitations would not be suited to my use case.

I ended up using a separate machine to host it. Thank you for your support
