### ISSUE TITLE
[BUG] Dial tcp port:i/o timeout when deploying MicroShift docker container on MacOS x86

### ISSUE THREAD

**Issue by MMMsc** [openshift/microshift#1386]
#### What happened?
Follow the doc to deploy Microshift image:

`  docker run -p 127.0.0.1:329:6443 -p 127.0.0.1:30095:9095 -p 127.0.0.1:30080:8080 quay.io/microshift/microshift-aio:latest`

The kubeconfig is described as follows:
`apiVersion: v1
kind: Config
current-context: microshift
preferences: {}
contexts:
- context:
    cluster: microshift
    namespace: default
    user: user
  name: microshift
clusters:
- cluster:
    server: https://172.17.0.2:6443
    certificate-authority-data: 
  name: microshift
users:
- name: user
  user:
    client-certificate-data: 
    client-key-data: `

When I execute `kubectl version` command and `dial tcp 172.17.0.2:6443: i/o timeout` occured.

#### What did you expect to happen?
the 6443 port from Microshift container is accesable from local host

#### How to reproduce it (as minimally and precisely as possible)?
1. Follow along `https://github.com/stolostron/multicluster-global-hub`.

#### Environment
- MicroShift version (use `microshift version`):
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`): macOS Monterey
- Kernel (e.g. `uname -a`):
- Others:

**Comment by ggiguash** [comment]
@MMMsc, thank you for reporting this issue. We no longer support running MicroShift in containers. The instructions in the microshift.io site are outdated and they may not work.
For up-to-date MicroShift installation instructions, please follow instructions from https://github.com/openshift/microshift site.

**Comment by ggiguash** [comment]
Closing this issue as the reported environment is not supported.
/close
