### ISSUE TITLE
Optionally start OpenShift components

### ISSUE THREAD

**Issue by rootfs** [openshift/microshift#144]
In the current implementation, all components in the `pkg/assets` are started. We need to fine tune the process to make the startup configurable and only turn on those that are allowed in the configuration file.

**Comment by guymguym** [comment]
Just to add on that I think that enabling components should also be possible after startup.
The reason I believe this is important to support on runtime is that the trigger to enable openshift components is when trying to deploy some workload that depends on it, and since workloads will not be bundled into microshift then this event will occur on runtime.

**Comment by rootfs** [comment]
@guymguym yes, the configuration file is watched, changes will be picked up to start other components if they are enabled during runtime.

**Comment by fzdarsky** [comment]
@rootfs could you provide an example use of this, please?
The set of components we deploy should anyway be limited to a bare minimum, with everything that's non-essential (say, a local registry) being something that users can deploy post cluster-up. Are you suggesting some of the components we deploy shouldn't belong to the essential minimal set? Or is the intention to make components replaceable?

**Comment by guymguym** [comment]
@fzdarsky One example of a feature that I wanted to enable post cluster-up is metrics which is not enabled by default on microshift. For example I stumbled this -
```
$ kubectl top pod
error: Metrics API not available
```
I'm not sure if metrics should be included in a bare minimum deployment, but I definitely hear requirements for metrics on Edge that includes also prometheus, which might also be a custom deployment configuration.

**Comment by copejon** [comment]
@guymguym 's use case either falls under pre-loading images (#162 ) or should be left to the user as a manual post-boot operation.

I think at this stage, we should remain opinionated about microshift's runtime services, lest we open a can of compatibility worms before we're ready to address them.  @rootfs ?
