### ISSUE TITLE
[HELP] How to configure the mirror harbor address so that pods can be deployed in microshift

### ISSUE THREAD

**Issue by AllenZMC** [openshift/microshift#1452]
How to configure the mirror harbor address so that pods can be deployed in microshift ?

**Comment by ggiguash** [comment]
From MicroShift side, review this document on how to configure proxies.
https://github.com/openshift/microshift/blob/main/docs/howto_http_proxy.md

If this is not sufficient, please provide more information on what you're trying to accomplish and what's not working

**Comment by AllenZMC** [comment]
Thanks @ggiguash 

For example, I want to deploy a pod. This pod needs a busybox image. This image is on the local self-built harbor. How to configure microshift to pull this image

**Comment by ggiguash** [comment]
@AllenZMC , for installing user workloads in MicroShift, you need to follow the procedure as described in [Auto-applying Manifests](https://github.com/openshift/microshift/blob/main/docs/howto_config.md#auto-applying-manifests).

In your manifests, you should be able to point to any registry of your own.

Does this answer your question?

**Comment by AllenZMC** [comment]
@ggiguash  Does it support manual deployment?

**Comment by ggiguash** [comment]
Certainly, you can use `oc` or `kubectl` commands to manually deploy your manifests on a MicroShift node.
