### ISSUE TITLE
[HELP] Will etcd data be lost if microshift restarts?

### ISSUE THREAD

**Issue by AllenZMC** [openshift/microshift#1466]
Will etcd data be lost if microshift restarts?

**Comment by ggiguash** [comment]
etcd data is persisted in /var/lib/microshift directory and it's not lost on MicroShift restart. 
To clean all the MicroShift-specific data, use the following script.
```
$ /usr/bin/microshift-cleanup-data 
Stop all MicroShift services, also cleaning their data

Usage: microshift-cleanup-data <--all | --ovn>
   --all   Clean all MicroShift and OVN data
   --ovn   Clean OVN data only
```

**Comment by AllenZMC** [comment]
@ggiguash  Thank you for your answer
