### ISSUE TITLE
[HELP] Does microshift have monitoring and alarm components like OCP?

### ISSUE THREAD

**Issue by AllenZMC** [openshift/microshift#1473]
Does microshift have monitoring and alarm components like OCP ?

**Comment by AllenZMC** [comment]
@dhellmann @ggiguash

**Comment by dhellmann** [comment]
MicroShift does not include monitoring or alarm tools. We will be working on making sure all of the useful metrics about MicroShift are available for collection in a future release.

**Comment by AllenZMC** [comment]
@dhellmann I get it, thanks！
