### ISSUE TITLE
[BUG] Build error for microshift with ocp 4.13 dependencies on RHEL 8

### ISSUE THREAD

**Issue by morvencao** [openshift/microshift#1593]
#### What happened?

When I follow https://github.com/openshift/microshift/blob/main/docs/rhel4edge_iso.md to build microshift ISO, I got the following error:

```bash
# ~/microshift/scripts/image-builder/build.sh -pull_secret_file ~/microshift/.pull-secret.json

# Checking available disk space

# Downloading local OpenShift and MicroShift repositories

# Loading sources for OpenShift and MicroShift

# Preparing blueprints

# Loading microshift-container blueprint v0.0.1
ERROR: BlueprintsError: microshift-container: DNF error occurred: RepoError: There was a problem reading a repository: Failed to download metadata for repo '7fb89dcf2be6c00fb8c4821c6c398327756fae6c2e280c679db87b75d848ced1' [openshift-local: file:///root/microshift/_output/image-builder/openshift-local/]: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

#### What did you expect to happen?

Build successfully

#### How to reproduce it (as minimally and precisely as possible)?
1. '...'
2. '...'

#### Environment
- MicroShift version (use `microshift version`):  microshift-4.14.0_0.nightly_2023_03_27
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`): rhel 8.7
- Kernel (e.g. `uname -a`):
- Others:

**Comment by morvencao** [comment]
The error is from this command during building:

```bash
# composer-cli blueprints depsolve microshift-container
ERROR: BlueprintsError: microshift-container: DNF error occurred:
RepoError: There was a problem reading a repository:
Failed to download metadata for repo '7fb89dcf2be6c00fb8c4821c6c398327756fae6c2e280c679db87b75d848ced1' 
[openshift-local: file:///root/microshift/_output/image-builder/openshift-local/]:
Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
blueprint: microshift-container v0.0.1
```

**Comment by ggiguash** [comment]
@morvencao , thank you for reporting this problem. 
We only support RHEL 9.x for the development and runtime environment for 4.13 onwards.
Please, review the https://github.com/openshift/microshift/blob/main/docs/devenv_setup.md#create-development-virtual-machine document for the supported OS list.

I'm closing this report for now. Feel free to reopen it if the problem occurs on a supported OS.

/close
