### ISSUE TITLE
[BUG] Documentation uses incompatible Go versioning

### ISSUE THREAD

**Issue by nicklesimba** [openshift/microshift#1758]
#### What happened?
When following microshift docs [this section](https://github.com/openshift/microshift/blob/main/docs/devenv_setup.md#configuring-vm) installs go version 1.18. When trying to run `make rpm` I encounter the error that a module requires go1.19 or above.

#### What did you expect to happen?
I expect the linked section to install the compatible Go version.

#### How to reproduce it (as minimally and precisely as possible)?
Follow microshift documentation from the beginning and you will encounter this issue.

**Comment by dhellmann** [comment]
Thanks for pointing that out, @nicklesimba . I think most of the developers are using the [automation for setting up the VM](https://github.com/openshift/microshift/blob/main/docs/devenv_setup_auto.md), and the script that uses correctly downloads the newer go compiler. We'll update the manual instructions, too.

**Comment by dhellmann** [comment]
I opened https://issues.redhat.com/browse/USHIFT-1235 for our internal tracking.

**Comment by nicklesimba** [comment]
It may be beneficial to new devs like me to provide a brief explanation at the top of the manual instructions document about differences between manual and automated setup.

**Comment by dhellmann** [comment]
Great point. I think we link in the other direction already, but we could point out that the automated scripts run in CI and are therefore being tested regularly. Ideally, of course, there would not be any differences.

**Comment by ggiguash** [comment]
@nicklesimba, what operating system are you using for the devenv setup? When using the latest RHEL 9.2 beta, it should come with the right compiler version.
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.2 Beta (Plow)

$ sudo dnf whatprovides golang
golang-1.19.4-1.el9.x86_64 : The Go Programming Language
Repo        : @System
Matched from:
Provide    : golang = 1.19.4-1.el9

golang-1.19.4-1.el9.x86_64 : The Go Programming Language
Repo        : rhel-9-for-x86_64-appstream-beta-rpms
Matched from:
Provide    : golang = 1.19.4-1.el9
```

**Comment by nicklesimba** [comment]
@ggiguash hi, yes I realized I need to be using 9.2 and was able to make it further in the installation. However in the docs we see this in the install script:
`ISONAME=rhel-baseos-9.1-$(uname -m)-boot.iso`
This was confusing to me, so it may be helpful to make this line reference a 9.2 image.
