### ISSUE TITLE
How etcd data is backed up and restored？

### ISSUE THREAD

**Issue by AllenZMC** [openshift/microshift#1772]
How etcd data is backed up and restored？

**Comment by AllenZMC** [comment]
@dhellmann How to restore the backup, copy it directly to the `/var/lib/microshift` directory?

**Comment by AllenZMC** [comment]
@dhellmann  How many container resources does microshift support, and how many resources does etcd support at most?

**Comment by AllenZMC** [comment]
How many pods does microshift support?

**Comment by dhellmann** [comment]
Yes, to restore the backup you would remove `/var/lib/microshift` and replace it with the backup content.

The storage limit for etcd is 8GB. Using that much storage does have an impact on RAM consumption, though.

We are optimizing for a small footprint, so the scale testing we are doing focuses on making things smaller, not necessarily supporting a large number of resources or pods. We have not imposed any hard limits, but would expect to have a very small number in a typical workload.

Can you tell me more information about your use case for MicroShift?

**Comment by AllenZMC** [comment]
@dhellmann  Because ocp single node supports 250 pods, so I want to know whether microshift also supports 250 pods.

**Comment by dhellmann** [comment]
The cap is set to 250 for MicroShift as well. As I said, though, we are not focusing on testing up to that scale. If you are running on a host that can run 250 pods, single-node OpenShift is probably a better fit.
