### ISSUE TITLE
[BUG] MicroShift RPM repos not found for ARM 

### ISSUE THREAD

**Issue by naveenrajm7** [openshift/microshift#1875]
#### What happened?
Microshift Installation in ARM machine failed ( AWS Graviton t4g )

#### What did you expect to happen?
RPM repos should be present to enable

#### How to reproduce it (as minimally and precisely as possible)?
1.  Fresh ARM machine with RHEL 9.2 registered with subscription-manager
2. Try enabling repos as shown in Docs

```bash
[ec2-user@ip-198-18-60-10 ~]$ sudo subscription-manager repos     --enable rhocp-4.13-for-rhel-9-$(uname -m)-rpms     --enable fast-datapath-for-rhel-9-$(uname -m)-rpm
Error: 'rhocp-4.13-for-rhel-9-aarch64-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.
Error: 'fast-datapath-for-rhel-9-aarch64-rpm' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.
```

#### Anything else we need to know?

I have No-Cost RedHat Developer Subsription. I checked the  Content Repositories  Provided by RedHat Openshift Container Platform Subscription and I was not able to find any packages related to aarch64. 

#### Environment
- MicroShift version (use `microshift version`): N.A (Tried both 4.12 and 4.13 Docs)
- Hardware configuration: AWS Graviton t4g.small 
- OS (e.g: `cat /etc/os-release`): Red Hat Enterprise Linux release 9.2 (Plow)
- Kernel (e.g. `uname -a`): Linux ip-198-18-60-10.ec2.internal 5.14.0-284.11.1.el9_2.aarch64 \#1 SMP PREEMPT_DYNAMIC Wed Apr 12 11:23:11 EDT 2023 aarch64 aarch64 aarch64 GNU/Linux
- Others:

#### Relevant logs 

```bash
Error: 'rhocp-4.13-for-rhel-9-aarch64-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.
Error: 'fast-datapath-for-rhel-9-aarch64-rpm' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.
```

Please let me know how can I access microshift packages for ARM machines.

Thanks

**Comment by dhellmann** [comment]
hi, @naveenrajm7 

You need a valid Red Hat developer subscription to access those repos. We are working on upstream builds that would not require a subscription, but that may take us a little while.

**Comment by naveenrajm7** [comment]
Hi @dhellmann 

Thank you for confirmation. I see ```RedHat Openshift Container Platform for ARM 64``` is not included in No-Cost Red Hat Developer Subscription for Individuals but is available in other paid ones . After  [Getting Started Docs](https://github.com/openshift/microshift/blob/main/docs/getting_started.md) was updated to include ARM64 instruction, the license mentioned was not updated. That caused confusion. 

Thanks!

**Comment by dhellmann** [comment]
New versions of OpenShift Local include MicroShift as an option, so if you're just wanting to try it out that may be an option. https://www.redhat.com/sysadmin/deploy-microshift-laptop has some instructions.

**Comment by ggiguash** [comment]
@naveenrajm7, thank you for reporting this problem.
Can you please re-open this issue? I'd like to fix the getting started docs to avoid confusion.

**Comment by DanielFroehlich** [comment]
This is actually a mishap in the Developer For Individual Subscripts. The two repos are missing, but they should be there. We will fix this in the subscription asap.

**Comment by ggiguash** [comment]
@naveenrajm7  it will take a week or two to fix the subscription. 
We will update this issue when done and ask you to verify before closing it.

**Comment by ggiguash** [comment]
@skonto, the issue has not been resolved yet. Unfortunately, it takes a bit longer than expected.
We'll update here as soon as we have it working - thank you for the patience.

**Comment by ggiguash** [comment]
@naveenrajm7 / @skonto, can you please re-check if `microshift` aarch64 RPMs can be accessed from a developer subscription now?
```
sudo subscription-manager repos --enable rhocp-4.13-for-rhel-9-aarch64-rpms
sudo subscription-manager repos --list-enabled | grep rhocp
dnf download microshift\*
```

**Comment by naveenrajm7** [comment]
Hi @ggiguash 

I am still not able to find `rhocp-4.13-for-rhel-9-aarch64-rpms` in Developer subsription. Not sure if it takes some time to reflect. I was also not able to find it in the [Subscription](https://access.redhat.com/management/subscriptions/product/RH00798) Content provided list in RedHat Customer portal.
I will check after a week and let you know if anything changes. 

```bash
[ec2-user@ip-198-18-60-10 ~]$ uname -r
5.14.0-284.11.1.el9_2.aarch64
[ec2-user@ip-198-18-60-10 ~]$ sudo subscription-manager repos --enable rhocp-4.13-for-rhel-9-aarch64-rpms
Error: 'rhocp-4.13-for-rhel-9-aarch64-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.
[ec2-user@ip-198-18-60-10 ~]$ sudo subscription-manager repos --list-enabled | grep rhocp
[ec2-user@ip-198-18-60-10 ~]$ sudo subscription-manager repos --list | grep rhocp
```

**Comment by ggiguash** [comment]
@naveenrajm7 , you're right. I created a RH Developer Subscription using my private email to test and the products are still not available on the aarch64 platform. Let me follow-up with the internal team again.
Sorry for this delay and thank you for your patience while we're figuring this out.

**Comment by ggiguash** [comment]
Chiming in to update this issue. Unfortunatelly, we're still working to resolve the problem with the MicroShift subscriptions on ARM64 platform.

**Comment by ggiguash** [comment]
Another update: we have enabled the SKUs, but the repos are still unavailable. Working with the involved teams on a resolution.

**Comment by ggiguash** [comment]
Chiming in here: SKUs are enabled by their propagation may take more time. I've just checked and it did not happen yet.

**Comment by ggiguash** [comment]
Looks like the RPM packages are available for developer subscription on AARCH64.
@skonto / @naveenrajm7 - can you confirm?

```
# sudo dnf search microshift
Updating Subscription Management repositories.
Red Hat OpenShift Container Platform 4.13 for RHEL 9 ARM 64 (RPMs)                                                                                            3.9 MB/s | 7.0 MB     00:01    
Last metadata expiration check: 0:00:01 ago on Fri 18 Aug 2023 06:40:47 AM UTC.
============================================================================= Name & Summary Matched: microshift =============================================================================
microshift.aarch64 : MicroShift service
microshift-greenboot.noarch : Greenboot components for MicroShift
microshift-networking.aarch64 : Networking components for MicroShift
microshift-release-info.noarch : Release information for MicroShift
microshift-selinux.noarch : SELinux policies for MicroShift
```

**Comment by naveenrajm7** [comment]
Hi @ggiguash 

Thank you for staying on top of this and getting it fixed for us. I can now see ```Red Hat OpenShift Container Platform for  ARM 64```  in RH Developer Subscription for Individuals.

This will help our LFX project where we are trying to get serverless working in microshift, you can check out our [Microshift-Serverless](https://github.com/naveenrajm7/microshift-serverless) project. 

Thanks!
