### ISSUE TITLE
[BUG] Having issues with setup script (manage-vm.sh)

### ISSUE THREAD

**Issue by nicklesimba** [openshift/microshift#1950]
#### What happened?
I tried to follow the setup procedure listed in `microshift/docs/devenv_setup.md`. 
My setup is as follows:
- Running a Fedora 37 server
- Download the rhel9.2 dvd image iso listed in the documentation (rhel-9.2-x86_64-dvd.iso)
- Move the iso to /var/lib/libvirt/images/
- Run the following:

```
VMNAME="microshift-dev"
git clone https://github.com/openshift/microshift.git ~/microshift
cd ~/microshift
./scripts/devenv-builder/manage-vm.sh create -n ${VMNAME}
```

I expect the VM to successfully be created, however I get this result:

```
error: failed to get domain 'microshift-dev'
Waiting for VM microshift-dev to have an IP
ERROR    Error validating install location: Could not find an installable distribution at URL '/var/lib/libvirt/images/rhel-9.2-x86_64-dvd.iso'

The location must be the root directory of an install tree.
See virt-install man page for various distro examples.
```

Previously, I was able to create the VM using the following command:

```
sudo -b bash -c " \
cd /var/lib/libvirt/images/ && \
virt-install \
    --name ${VMNAME} \
    --vcpus 2 \
    --memory 4096 \
    --disk path=./${VMNAME}.qcow2,size=50 \
    --network network=default,model=virtio \
    --os-type generic \
    --events on_reboot=restart \
    --cdrom ./${ISONAME} \
    --wait \
"
```

...but it appears that this method of installing is deprecated as it is currently removed from the documentation. 

A halfway workaround is to disregard the current documentation approach and use the command I posted above. However, this method requires configuration of the VM via GUI - which I am unable to do as the server I am running on is CLI-only. As far as I understand, with the current documentation, the `manage-vm.sh` script automates the install-wizard process, or at least does it via CLI, and avoids needing access to a GUI.

#### What did you expect to happen?
I'm hoping to either understand what I am doing wrong, or if the documentation has a mistake, fix the documentation after identifying the problem.

#### How to reproduce it (as minimally and precisely as possible)?
On an unconfigured environment, run the setup as specified in the documentation, up until the "Configuring VM" section.

#### Anything else we need to know?
Squirrels can fall from 30 meters high, without hurting themselves.

#### Environment
- MicroShift version (use `microshift version`): latest master branch as of 6/22/23
- OS (e.g: `cat /etc/os-release`): Fedora 37 (host), RHEL 9.2 x86_64 (iso used for VM)

**Comment by nicklesimba** [comment]
@ggiguash @dhellmann hi folks, tagging because you were both very helpful last time when I had documentation questions. :)

**Comment by dhellmann** [comment]
The message 

```
Error validating install location: Could not find an installable distribution at URL '/var/lib/libvirt/images/rhel-9.2-x86_64-dvd.iso'
```

Makes it seem like there is something wrong with that file. What are the permissions? Is it a valid ISO image?

**Comment by nicklesimba** [comment]
The file permission is "-rw-r--r--" which I understand to mean all read/write permissions are granted to users (I'm running as root by the way). I was The iso image should be valid since it comes directly from the documentation's link. File name: rhel-9.2-x86_64-dvd.iso

**Comment by ggiguash** [comment]
@nicklesimba , can you post the output of the following command run on your hypervisor host?
```
sudo ls -l /var/lib/libvirt/images/
```

**Comment by nicklesimba** [comment]
Here is the output of those commands:
```
[root@sdn-07 microshift]# sudo ls -l /var/lib/libvirt/images/rhel-9.2-x86_64-dvd.iso
sudo md5sum /var/lib/libvirt/images/rhel-9.2-x86_64-dvd.iso
-rw-r--r--. 1 root root 45759 Jun 26 14:06 /var/lib/libvirt/images/rhel-9.2-x86_64-dvd.iso
44f720c530dbaab245cea5f336985a1b  /var/lib/libvirt/images/rhel-9.2-x86_64-dvd.iso
```

Here is the full error output as well, in case it helps:

```
[root@sdn-07 microshift]# ./scripts/devenv-builder/manage-vm.sh create -n ${VMNAME}
Creating VM microshift-dev from /var/lib/libvirt/images/rhel-9.2-x86_64-dvd.iso ...
Last metadata expiration check: 1:06:34 ago on Mon 26 Jun 2023 01:03:30 PM EDT.
Package libvirt-8.6.0-5.fc37.x86_64 is already installed.
Package virt-manager-4.1.0-1.fc37.noarch is already installed.
Package virt-install-4.1.0-1.fc37.noarch is already installed.
Package virt-viewer-11.0-5.fc37.x86_64 is already installed.
Package libvirt-client-8.6.0-5.fc37.x86_64 is already installed.
Package qemu-kvm-2:7.0.0-15.fc37.x86_64 is already installed.
Package qemu-img-2:7.0.0-15.fc37.x86_64 is already installed.
Package sshpass-1.09-4.fc37.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
error: failed to get domain 'microshift-dev'
Waiting for VM microshift-dev to have an IP
ERROR    Error validating install location: Could not find an installable distribution at URL '/var/lib/libvirt/images/rhel-9.2-x86_64-dvd.iso'

The location must be the root directory of an install tree.
See virt-install man page for various distro examples.
^C
```

**Comment by nicklesimba** [comment]
It appears the download through command line (using wget command) was failing and downloading something else entirely, as evidenced by running the file command:

```
/var/lib/libvirt/images/rhel-9.2-x86_64-dvd.iso: HTML document, Unicode text, UTF-8 text, with very long lines (600)
```

I believe this is because the website for downloading the iso requires Red Hat sso login. When you click the "download" button it redirects to a login prompt, and if you're logged in, it redirects to an automatic download. However, the Fedora 37 server I'm running on is CLI only, so I can't do any of this. Is there a way to get the iso via command line?

My current workaround is to download the iso separately from the Fedora 37 server (on my local work laptop) and sshcopy the file over.

**Comment by nicklesimba** [comment]
I am clicking the URL provided in the docs (https://developers.redhat.com/products/rhel/download) and once authenticated/logged in, I copy the url of the red button "Download RHEL at no cost", which gives me this url: https://developers.redhat.com/content-gateway/file/rhel/9.2/rhel-9.2-x86_64-dvd.iso

Where is the token that you're describing? Am I missing a step still?

**Comment by dhellmann** [comment]
Ah, I usually start from https://access.redhat.com/downloads/content/rhel but I don't know if that's accessible to free accounts.

If not, I'm not sure I have a better answer for you than what you're already doing, unfortunately.

**Comment by nicklesimba** [comment]
Okay, I can access that link and I see what you mean, thanks! Though, for users who can't, hopefully this thread is helpful since using the scp command works just fine.

**Comment by ggiguash** [comment]
@nicklesimba , looks like we figured out the problem, so I'm closing the issue for now.
/close
