### ISSUE TITLE
[BUG] ./scripts/devenv-builder/configure-vm.sh: nothing provides openshift-clients needed by microshift

### ISSUE THREAD

**Issue by IceCodeNew** [openshift/microshift#1965]
#### What happened?
I was following the steps of [docs/devenv_setup.md](https://github.com/openshift/microshift/blob/42021b5d6b94719e2ad5ffbcb9cd1500b84126a0/docs/devenv_setup.md) to set up a development environment.
The script `configure-vm.sh` failed with the following error:
```
Error: 
 Problem: conflicting requests
  - nothing provides openshift-clients needed by microshift-4.14.0_0.nightly_2023_06_20_065807_20230626095221_42021b5d6-1.el9.x86_64 from @commandline
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

#### What did you expect to happen?
The script `configure-vm.sh` should be able to install the openshift clients without depending on the repositories of RHEL.

#### How to reproduce it (as minimally and precisely as possible)?
1. Create a brand new VM with the latest CentOS 9 Stream ISO
2. Clone this repo under the home dir of user microshift
3. `ssh microshift@${VMIPADDR} "~/configure-vm.sh ~/.pull-secret.json"`

#### Environment
- MicroShift version (use `microshift version`): `has nothing to do here`
- Hardware configuration: `AMD64, 4C8G, 200GB storage`
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```
- Kernel (e.g. `uname -a`):
```
Linux VM-0-2-centos 5.14.0-325.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun 9 19:47:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ggiguash** [comment]
The `openshift-client` RPM dependency was added in https://github.com/openshift/microshift/pull/1376 and it broke the instructions for installing on CentOS.

**Comment by ggiguash** [comment]
On CentOS, we could download and install `openshift-clients` RPM from the mirror repository.

For example:
```
curl -s https://mirror.openshift.com/pub/openshift-v4/dependencies/rpms/4.14-el9-beta/ | grep -o "openshift-clients-4[^\"']*.rpm" | sort | uniq
openshift-clients-4.14.0-202306270854.p0.gc078876.assembly.stream.el9.x86_64.rpm
```
