### ISSUE TITLE
[Enhancement]: Add rootless mode for microshift

### ISSUE THREAD

**Issue by fsdrw08** [openshift/microshift#2069]
#### What would you like to be added?
add rootless mode for microshift

#### Why is this needed?
I think rootless mode is more safty to run in a edge device

**Comment by dhellmann** [comment]
Thanks, @fsdrw08. When Kubernetes fully supports running rootless, we will look at what it would take to make MicroShift able to run rootless, too. At this point, though, I'm not aware of that being fully supported upstream.

**Comment by ggiguash** [comment]
Closing this issue for now as there is not much we can do at the moment.
/close
