### ISSUE TITLE
[BUG] MicroShift machine no longer accessible via ssh

### ISSUE THREAD

**Issue by adelton** [openshift/microshift#2161]
#### What happened?

I followed https://microshift.io/docs/getting-started/ and installed MicroShift from @redhat-et/microshift-testing copr repo on RHEL 8.8. After `systemctl enable microshift --now` the ssh connection hangs up.

Investigating `ip a` output before installation and after it, it seems the IP address got moved from `ens3` network interface to `br-ex` but for some reason I cannot connect to the ssh over that IP address anymore.

#### What did you expect to happen?

I expected my ssh connection to stay uninterrupted, or at worse, be able to recreate that connection 

#### How to reproduce it (as minimally and precisely as possible)?
1. Have RHEL 8.8 installed.
2. `dnf copr enable -y @redhat-et/microshift-testing`
3. `dnf install -y microshift`
4. Get pull secret to `/etc/crio/openshift-pull-secret`
5. `systemctl enable microshift --now`

#### Anything else we need to know?

We saw this issue with https://github.com/openshift/microshift/issues/1061. It then went away and now it seems to be back.

I also seem to observe the same behaviour with microshift-4.13.6-202307200823.p0.g694973d.assembly.4.13.6.el9.x86_64 from rhocp-4.13-for-rhel-9-x86_64-rpms on RHEL 9.2

#### Environment
- MicroShift version (use `microshift version`):
```
MicroShift Version: 4.12.0-0.microshift-2022-11-17-084702-untagged
Base OCP Version: 4.12.0-0.nightly-2022-11-07-181244
```
- Hardware configuration: this is a VM on some host.
- OS (e.g: `cat /etc/os-release`):
```
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"

```
- Kernel (e.g. `uname -a`):
```
Linux machine.example.com 4.18.0-477.22.1.el8_8.x86_64 #1 SMP Thu Jul 27 12:13:10 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
```
- Others:

**Comment by ggiguash** [comment]
@adelton , the document you used is outdated. While it can probably be searched in the internet, the top-level microshift.io page now references https://github.com/openshift/microshift/blob/main/docs/user/getting_started.md as getting started instructions.

Please, follow the up-to-date instructions for installing MicroShift.

**Comment by adelton** [comment]
It turns out this was a PEBKAC -- I happened to be accessing the machine from workstation in network 10.43.0.0, which per https://access.redhat.com/documentation/en-us/red_hat_build_of_microshift/4.13/html-single/configuring/index#microshift-yaml-default_microshift-configuring happens to be `serviceNetwork`, and thus not externally routable from the MicroShift machine.

After changing the values in `/etc/microshift/config.yaml`, things work as expected.
