### ISSUE TITLE
Import Image from tar file

### ISSUE THREAD

**Issue by nomi-ramzan** [openshift/microshift#2272]
I downloaded minishift image using podman and now I am trying to run that image to microshift with/without image registery. I tried 

`oc import-image devfile-sample-git ./devfile-sample-git.tar --confirm`
Error:
`Error from server (InternalError): Internal error occurred: images.config.openshift.io "cluster" not found`

`oc import-image ./devfile-sample-git.tar --confirm`
Error:
`error: the image name must be a valid container image pull spec or reference to an image stream (e.g. myregistry/myteam/image:tag)`

How can I import and run image ?

**Comment by dhellmann** [comment]
MicroShift does not include the internal registry that OpenShift has. You'll need a registry, or you'll need to incorporate that image into the blueprint for your ostree image so it is included in the read-only crio cache location.

**Comment by nomi-ramzan** [comment]
> You'll need a registry, or you'll need to incorporate that image into the blueprint for your ostree image so it is included in the read-only crio cache location.
Can you please explain this option further of give me any guide where I can read how to do this ?

**Comment by dhellmann** [comment]
Maybe if you could explain a little more about what you're trying to do, I could give you some better advice. For example, you say you downloaded the image with podman. Why not just configure a Pod in MicroShift to use that image directly?

**Comment by nomi-ramzan** [comment]
I am trying to run nodejs application on Microshift. And because microshift can not built image so I have minishift to build that image (nodejs + app code). then I download this image using podman in .tar file. Now I am trying to run same image (.tar file) on microshift. 
And  as you said

> Why not just configure a Pod in MicroShift to use that image directly?

Can you help me how to configure the pod then ?

**Comment by dhellmann** [comment]
The kubernetes tutorials should help with that. https://kubernetes.io/docs/concepts/workloads/controllers/deployment/ for example.

**Comment by nomi-ramzan** [comment]
Resolved.
