### ISSUE TITLE
[BUG] There are no new builds in the repo for Fedora IoT

### ISSUE THREAD

**Issue by pablo-suazo** [openshift/microshift#2494]
I am trying to deploy Fedora IoT 38 & Microshift on a Raspberry Pi 4.

Microshift is not launching correctly, I was checking and the build is 4.8.0 and not for Fedora 38.

I was checking the repos and there are no new builds for 1,5 year now.

There are plans to start building Microshift again for Fedora IoT?

Find attached some screenshots of the actual status of the repos.

![image](https://github.com/openshift/microshift/assets/102029997/076a3a0a-78c6-4ca7-80aa-7eccb1316ee8)

![image](https://github.com/openshift/microshift/assets/102029997/9aa266ad-bb70-4698-8db5-7418b8bd87ae)

![image](https://github.com/openshift/microshift/assets/102029997/276776f9-e3f6-4fb7-b5ce-4d1579ca4dbd)

**Comment by dhellmann** [comment]
Hi, @pablo-suazo , unfortunately the team has had to focus on some productization work, and that has meant pausing some community work like this. We do intend to get back to creating Fedora builds, but I can't promise a timeline.
