### ISSUE TITLE
USHIFT-17: Increase Unit Test Coverage of MicroShift code

### ISSUE THREAD

**Issue by osilkin98** [openshift/microshift#273]
#### What would you like to be added:
Unit/Integration testing framework for Microshift. 

We will need to determine whether to adhere to behavior-driven development vs. test-driven development. 

#### Why is this needed:
Currently, there is no way to verify that core components of the platform work without manually running `make build` and running the binary under custom scenarios manually. Developers would greatly benefit from being able to run tests that automatically verify whether or not their changes have broken anything.

**Comment by ggiguash** [comment]
/retitle USHIFT-17: Increase Unit Test Coverage of MicroShift code
