### ISSUE TITLE
[BUG] microshift.io links to github.com for documentation

### ISSUE THREAD

**Issue by ianb-mp** [openshift/microshift#2833]
#### What happened?

When browsing https://microshift.io/ the documentation links are to github.com instead of microshift.io

#### What did you expect to happen?

Documentation should link to pages on the microshift.io website itself e.g. 

Instead of linking to: https://github.com/openshift/microshift/blob/main/docs/user/getting_started.md
Link to this: https://microshift.io/docs/getting-started/

If the doco on microshift.io is out-of-date and not to be used, then please either remove that doco or put a warning at the top of the page to say that it is not current and that other doco should be used.

#### How to reproduce it (as minimally and precisely as possible)?
1. Browse to https://microshift.io
2. Click any of the links/buttons for documentation
3. Observe that you are taken to github.com

#### Environment
- MicroShift version (use `microshift version`):
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by dhellmann** [comment]
The team has been focusing on product work, and hasn't had time to update the microshift.io site. We hope to have time to do that soon. In the mean time, https://access.redhat.com/documentation/en-us/red_hat_build_of_microshift/4.14 has the most up to date information.
