### ISSUE TITLE
[BUG] rpm repo redhat-et has old version v4.8.0

### ISSUE THREAD

**Issue by ianb-mp** [openshift/microshift#2840]
#### What happened?

I followed the install instructions here: https://microshift.io/docs/getting-started/ and ended up with rpm package `4.8.0-2022_04_20_141053.el9`

#### What did you expect to happen?

There should be a more recent version of microshift available from rpm repo: https://copr.fedorainfracloud.org/coprs/g/redhat-et/microshift/

**Comment by dhellmann** [comment]
The team has not had capacity to resume COPR builds, but there are pre-release RPMs available from the releases page here on GitHub (https://github.com/openshift/microshift/releases). The docs on microshift.io are for the COPR builds. You will find product documentation for more recent versions on the RedHat portal (https://access.redhat.com/documentation/en-us/red_hat_build_of_microshift/4.14). A free developer account there should give you access to everything you need to see the docs and access the RHEL package repositories.
