### ISSUE TITLE
[BUG] <Security: SSL Medium Strength Cipher Suites Supported>

### ISSUE THREAD

**Issue by lance5890** [openshift/microshift#2974]
#### What happened?

1. while the kube-apiserver and etcd has already suppuort the  Strength Cipher Suites 
2. The kube-controller-manager, kube-scheduler, kubelet need to also suppuort Strength Cipher Suites 
#### How to reproduce it (as minimally and precisely as possible)?
1. '...'
3. '...'

#### Environment
- MicroShift version (use `microshift version`):
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by codespearhead** [comment]
This issue was fixed in PR #2973, but since [that PR is not linked to this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#about-linked-issues-and-pull-requests) due to a typo, it was not closed automatically.

@lance5890 Can you close it?

**Comment by lance5890** [comment]
> This issue was fixed in PR #2973, but since [that PR is not linked to this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#about-linked-issues-and-pull-requests) due to a typo, it was not closed automatically.
> 
> @lance5890 Can you close it?

ok
