### ISSUE TITLE
[Enhancement]: MicroShift Health Check

### ISSUE THREAD

**Issue by lahorite** [openshift/microshift#302]
#### What would you like to be added:
Monitoring Platform/Cluster
Monitoring Nodes
Monitoring Pods
Containers status
Pods per Node
Services Health
Resources Utilization (CPU/Memory/Network)
etc.

#### Why is this needed:
Give end-user visibility, on the state and health of their applications and solutions
Very important for the mission-critical applications

**Comment by guymguym** [comment]
@husky-parul Are we looking for something roughly like https://github.com/kubernetes/dashboard ?

**Comment by guymguym** [comment]
> If I am an admin responsible for managing Kube clusters. What metrics, do I need to know, for the health check of my Kube clusters?

@cooktheryan WDYT ^ ?

**Comment by cooktheryan** [comment]
I think at minimum we need to know network, cpu, and memory utilization for host and possibly the same for pods.

**Comment by guymguym** [comment]
I think the kubernetes dashboard can do that. It gets usage data from the metrics server and I know it has cpu and memory graphs per node/pod but I didn't see if it has network data... also what about production - do we need to collect this centrally? I wonder what footprint metrics-server + dashboard have compared to prometheus + grafana.

**Comment by husky-parul** [comment]
Problem is conventional Cloud focused monitoring is not going to work on edge clusters for reason:
Minimal resource footprint
Limited on site storage
Limited network

We need to have a monitoring solution that can give health checks and metrics on minimal far edge clusters. Limited cluster data can be stored on site. The option should provide a mechanism to scrape and push edge data and be able to process the data to perform metrics and health checks. Things to note:

The API servers on Edge Device (ED) could not be accessed from outside , they could be disconnected or behind a firewall. They will have limited storage capacity.

A solution that will work for us should have a mechanism to scrape data, push it to storage as soon as and when the network is available. I am exploring if we can achieve this by Kubernetes Dashboard. From reading the docs it looks like it uses a backend that interacts with the Kube APIs. 
https://github.com/kubernetes/dashboard/blob/master/docs/developer/architecture.md
I still need to find the answers whether it can push data to the frontend ad hoc or it depends on live calls. If the dashboard frontend makes live calls to the backend, we will run into situations when at times the backend is offline.

**Comment by cooktheryan** [comment]
Would it be possible to code the endpoints so that it's possible to use whatever the customer prefers? As long as Prometheus or kube dash can scrape it that's all we should care about. I push back because of those customers that are not at far edge and have a usable connection. They may want to opt to go with Prometheus to Thanos because its been proven tech to collate multiple clusters graphs together

**Comment by husky-parul** [comment]
Using Tanos/Prometheus or many other tools is upto the user depending on their cluster capacity and requirements. Via this issue, we aim to provide a suggestion for light weight monitoring tool that can support n/w limitations. As of now I haven't found an existing tool that can do this. While this might be a stretch and outside project scope, this issue might give us a generic monitoring tool for far edge devices with limited n/w.

**Comment by cooktheryan** [comment]
:+1:

**Comment by husky-parul** [comment]
@lahorite This is the view of kubernetes/dashboard UI
![image](https://user-images.githubusercontent.com/24639524/140372796-d90929a2-2d99-46e9-a2ba-cafd9d2b0301.png)

You can get the workload status, pod mem/cpu usage. You can add/delete workload and have access to logs and events. As long as you are able to access the cluster over n/w, you should be able to access the dashboard. I will update the docs on how to enable it soon.

**Comment by fzdarsky** [comment]
> Is it something that will suffice the requirements?

I believe it should be ok for this particular use case. However, as it doesn't match the MicroShift design goals (esp. that it must not require remote access to deployment and work under _all_ networking conditions), I feel it's not something we should document as permanent solution.

**Comment by cooktheryan** [comment]
https://prometheus.io/blog/2021/11/16/agent/
