### ISSUE TITLE
[BUG]  Unsure whether to enable remote remediations for RHEL 9

### ISSUE THREAD

**Issue by pwright** [openshift/microshift#3185]
####  Following instructions in Getting Started and don't know how to proceed

When downloading RHEL ISO, I'm prompted with this during registration:

![image](https://github.com/openshift/microshift/assets/5154224/555cf3eb-ec06-4a0c-a6dc-bde9db6b5873)

#### What did you expect to happen?

Some advice about enabling/disabling remote remediations

I'd like to know the setting that's used for testing so that I'm aligned with the most model usage of microshift.

#### How to reproduce it (as minimally and precisely as possible)?
1.  Follow https://github.com/openshift/microshift/blob/main/docs/user/getting_started.md
2.  On https://console.redhat.com/insights/image-builder/imagewizard?source=RHD#SIDs=&tags= 
You will be prompted to 'enable remote remediations'

#### Environment

No environment yet.

- MicroShift version (use `microshift version`):
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by pwright** [comment]
To update my own issue, I was looking at wrong place, using image builder instead of downloading the 9.2 ISO

**Comment by pwright** [comment]
The developers download page is pushing image builder as the method of getting a RHEL ISO. I've created #3186 to try and guide users to navigate to the direct 9.2 fiel

**Comment by ggiguash** [comment]
Closing the issue as the documentation fix merged
/close
