### ISSUE TITLE
Move all-in-one-with-gpu-support to microshift-documentation

### ISSUE THREAD

**Issue by sallyom** [openshift/microshift#423]
https://github.com/redhat-et/microshift/tree/main/hack/all-in-one  this needs to be migrated to the documentation site, probably here:
microshift-documentation/content/docs/deployment-modes/microshift-aio-with-gpu-support

**Comment by fzdarsky** [comment]
Before we can promote this hack to 'official', we need to close on the discussion whether it's mandatory that it'd be included in MicroShift core vs whether it can be deployed "on top". If it has to be part of MicroShift core, it must be in both MicroShift and AIO images. If not, it should be part of a documentation "how to".
