### ISSUE TITLE
[BUG] AIO works with cgroups v2 enabled, does not work with cgroups V1

### ISSUE THREAD

**Issue by sallyom** [openshift/microshift#551]
With MicroShift-AIO: 
Pods fail to start with cgroups v1 (CentOS 8 Stream)
Containerized CRI-O requires cgroups v2, seems like

Workaround
Run system with cgroups v2
([here's how to enable cgroups v2](https://gist.github.com/sallyom/6063d143b18142f0aa09bf36f11c2297#gistcomment-3901494))
Then, this works:
```
sudo podman run -d --rm --name microshift --privileged -v microshift-data:/var/lib -p 6443:6443 quay.io/microshift/microshift-aio:latest
```

**Comment by cooktheryan** [comment]
@sallyom can we document this in the docs repo?
