### ISSUE TITLE
USHIFT-22: microshift will not boot if the host has no internet connection

### ISSUE THREAD

**Issue by mangelajo** [openshift/microshift#553]
#### What happened:

Booting microshift with ethernet disconnected failed

#### What you expected to happen:

To boot and services to come up.

#### How to reproduce it (as minimally and precisely as possible):

Start a system with ethernet link down, try to start microshift.

#### Environment:
- Microshift version (use `microshift version`):
MicroShift Version: 4.8.0-0.microshift-2021-11-19-115908-14-g18aff6b
Base OKD Version: 4.8.0-0.okd-2021-10-10-030117

- Hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

#### Relevant Logs 

```
ene 11 18:18:37 jetson-tx2.local systemd[1]: Started MicroShift.
ene 11 18:18:37 jetson-tx2.local microshift[7819]: time="2022-01-11T18:18:37+01:00" level=fatal msg="failed to get host IP: no default r
ene 11 18:18:37 jetson-tx2.local systemd[1]: microshift.service: Main process exited, code=exited, status=1/FAILURE
ene 11 18:18:37 jetson-tx2.local systemd[1]: microshift.service: Failed with result 'exit-code'.
```

**Comment by mangelajo** [comment]
```Jan 21 14:10:52 microshift.local microshift[4888]: {"level":"info","ts":"2022-01-21T14:10:52.513Z","caller":"embed/serve.go:191","msg":"serving client traffic securely","address":"127.0.0.1:2379"}
Jan 21 14:10:52 microshift.local microshift[4888]: time="2022-01-21T14:10:52Z" level=info msg="kube-apiserver stopped: kube-apiserver configuration error: Unable to find suitable network address.error='no default routes found in \"/proc/net/route\" or \"/proc/net/ipv6_route\"'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this."
Jan 21 14:11:52 microshift.local microshift[4888]: time="2022-01-21T14:11:52Z" level=warning msg="kube-apiserver readiness check timed out: <nil>"
```
now this ^ 

We need to pass down the address to the kube-api server, instead of letting itself guess it.

**Comment by ggiguash** [comment]
/retitle USHIFT-22: Microshift will not boot if the host has no assigned IP address / ethernet connection

**Comment by zshi-redhat** [comment]
MicroShift is able to run without internet connection, but it needs to have an IP address assigned since node needs to have an IP, kubelet/kube-api requires that IP address to run.

**Comment by zshi-redhat** [comment]
/retitle USHIFT-22: microshift will not boot if the host has no internet connection
