### ISSUE TITLE
[BUG] non standard cluster.local domain in microshift breaks internal cluster DNS

### ISSUE THREAD

**Issue by mangelajo** [openshift/microshift#563]
#### What happened:

For example, under a microshift.home cluster domain, resolution of services like service.namespace.svc.microshift.home fails.

#### What you expected to happen:

Resolution to work.

#### How to reproduce it (as minimally and precisely as possible):

Install microshift with a domain different to cluster.local

#### Anything else we need to know?:

It can be fixed by updating the dns-default configmap to look up for $DOMAIN in the kubernetes section instead of cluster.local

#### workaround

For now stick to the default cluster domain name, or edit the dns-default configmap to replace the domain name.

**Comment by kpouget** [comment]
I confirm the problem and the workaround:
```
data:
  Corefile: |
    .:5353 {
        bufsize 512
        errors
        health {
            lameduck 20s
        }
        ready
        kubernetes in-addr.arpa ip6.arpa MY_CUSTOM_DOMAIN_HERE {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus 127.0.0.1:9153
        forward . /etc/resolv.conf {
            policy sequential
        }
        cache 900 {
            denial 9984 30
        }
        reload
    }
kind: ConfigMap
metadata:
  name: dns-default
  namespace: openshift-dns
```
after hours trying to understand what I was doing wrong with `Services`, I found out that it wasn't exactly my fault 🙃

**Comment by scholzj** [comment]
I run into this issue as well. It seems a bit weird that the same `.cluster.domain` field form the configuration file ends up being used for both:
* Internal cluster domain for the internal DNS used for communication between pods
* The external cluster DNS name used the OpenShift Router

These are not the same (at least in my case) - so I can get only one of them working at a time.
