### ISSUE TITLE
[BUG] 'Getting started' may confuse between RPM and Podman based deployments

### ISSUE THREAD

**Issue by mykaul** [openshift/microshift#604]
In each step, you need, if you chose RPM, to pick the right tab. What happened is that I picked the RPM tab in https://microshift.io/docs/getting-started/#deploying-microshift but then the next step (https://microshift.io/docs/getting-started/#copy-kubeconfig ) was still on 'Podman' tab, which was confusing.

**Comment by dhellmann** [comment]
The team is dropping support for deploying via podman and focusing on systemd and RPM packaging for RHEL. When we resume work on the community release we will update the documentation to remove the podman instructions entirely.
