### ISSUE TITLE
Failed to start MicroShift Containerized. Rocky Linux 8.5 on Raspberry Pi 4

### ISSUE THREAD

**Issue by mmurph3** [openshift/microshift#639]
#### What happened:
Installed microshift via https://microshift.io/docs/getting-started/ 
 And pods are failing to start successfully - stuck in pending.
#### What you expected to happen:
Expected containers to start succesfully
#### How to reproduce it (as minimally and precisely as possible):

1. Follow steps to install microshift on raspberry pi 4 running Rocky Linux 8.5 https://microshift.io/docs/getting-started/
2. oc get pods -A

NAMESPACE              NAME                                  READY   STATUS    RESTARTS   AGE
kube-system            pod/kube-flannel-ds-v2rn7             0/1     Pending   0          5s
openshift-dns          pod/dns-default-bcmsp                 0/2     Pending   0          5s
openshift-dns          pod/node-resolver-85j6s               0/1     Pending   0          5s
openshift-ingress      pod/router-default-85bcfdd948-p5nsg   0/1     Pending   0          55s
openshift-service-ca   pod/service-ca-7764c85869-kwffp       0/1     Pending   0          56s

#### Anything else we need to know?
This also happens following installing Using Microshift for Application Development

https://microshift.io/docs/getting-started/#using-microshift-for-application-development

#### Environment:
- Microshift version (use `microshift version`): 

MicroShift Version: 4.8.0-0.microshift-2022-03-11-124751
Base OKD Version: 4.8.0-0.okd-2021-10-10-030117

- Hardware configuration: Raspberry Pi 4 8GB RAM 120 GB SD
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per cluster: 4
Socket(s):           -
Cluster(s):          1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
CPU max MHz:         1500.0000
CPU min MHz:         600.0000
BogoMIPS:            108.00
Flags:               fp asimd evtstrm crc32 cpuid

- OS (e.g: `cat /etc/os-release`): 
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"

- Kernel (e.g. `uname -a`): 5.10.78-v8.1.el8
- Others:

#### Relevant Logs 

$ sudo journalctl -u microshift
-- Logs begin at Fri 2018-06-22 11:11:50 UTC, end at Sat 2022-03-26 02:23:29 UTC. --
Mar 26 01:09:32 bruce systemd[1]: Starting MicroShift Containerized...
Mar 26 01:09:33 bruce podman[20093]: Trying to pull quay.io/microshift/microshift:latest...
Mar 26 01:09:33 bruce podman[20093]: Getting image source signatures
Mar 26 01:09:33 bruce podman[20093]: Copying blob sha256:494c9773d08c19ddc9d8b718b9898616597b1b8f4707351a3ac061f01061cbce
Mar 26 01:09:33 bruce podman[20093]: Copying blob sha256:19bee6876ee37553a567063969d2025826447e5d8a4b944d1939c362613ce618
Mar 26 01:09:33 bruce podman[20093]: Copying blob sha256:7f51321f8c4d4f971aed59bbcef003e92a2b7b9f8d295b37ebec9da54c26428a
Mar 26 01:09:33 bruce podman[20093]: Copying blob sha256:0be3345e1f970d4a5a97178034affb01e65079fb1579dcfa34a0ae4970a4bb51
Mar 26 01:09:33 bruce podman[20093]: Copying blob sha256:433cb2d010a3a485e5ff64b238190c2254af9796ba2b607f3146b5bca87cdb42
Mar 26 01:09:33 bruce podman[20093]: Copying blob sha256:93c9655dd8881cca1ccf0fb6cc8ad4f2f5841861f68a6d750c124c47013c8bc1
Mar 26 01:09:34 bruce podman[20093]: Copying blob sha256:93c9655dd8881cca1ccf0fb6cc8ad4f2f5841861f68a6d750c124c47013c8bc1
Mar 26 01:09:34 bruce podman[20093]: Copying blob sha256:19bee6876ee37553a567063969d2025826447e5d8a4b944d1939c362613ce618
Mar 26 01:09:34 bruce podman[20093]: Copying blob sha256:433cb2d010a3a485e5ff64b238190c2254af9796ba2b607f3146b5bca87cdb42
Mar 26 01:09:34 bruce podman[20093]: Copying blob sha256:7f51321f8c4d4f971aed59bbcef003e92a2b7b9f8d295b37ebec9da54c26428a
Mar 26 01:09:34 bruce podman[20093]: Copying blob sha256:0e9fdba416109daa6208685268864e17b13911051ae4c72da471f65a0deaed1f
Mar 26 01:09:34 bruce podman[20093]: Copying blob sha256:494c9773d08c19ddc9d8b718b9898616597b1b8f4707351a3ac061f01061cbce
Mar 26 01:09:34 bruce podman[20093]: Copying blob sha256:0be3345e1f970d4a5a97178034affb01e65079fb1579dcfa34a0ae4970a4bb51
Mar 26 01:09:34 bruce podman[20093]: Copying blob sha256:0e9fdba416109daa6208685268864e17b13911051ae4c72da471f65a0deaed1f
Mar 26 01:09:50 bruce podman[20093]: Copying config sha256:aa7ce20d50321bfc6e60e063a499ba0f46db8c25888b5c0cc379caaa2cf4d785
Mar 26 01:09:50 bruce podman[20093]: Writing manifest to image destination
Mar 26 01:09:50 bruce podman[20093]: Storing signatures
Mar 26 01:09:50 bruce podman[20093]: Error: statfs /var/run/crio/crio.sock: no such file or directory
Mar 26 01:09:50 bruce systemd[1]: microshift.service: Main process exited, code=exited, status=125/n/a
Mar 26 01:09:50 bruce podman[20190]: Error: error reading CIDFile: open /run/microshift.service.ctr-id: no such file or directory
Mar 26 01:09:50 bruce systemd[1]: microshift.service: Control process exited, code=exited status=125
Mar 26 01:09:50 bruce systemd[1]: microshift.service: Failed with result 'exit-code'.
Mar 26 01:09:50 bruce systemd[1]: Failed to start MicroShift Containerized.
Mar 26 01:09:50 bruce systemd[1]: microshift.service: Service RestartSec=100ms expired, scheduling restart.
Mar 26 01:09:50 bruce systemd[1]: microshift.service: Scheduled restart job, restart counter is at 1.
Mar 26 01:09:50 bruce systemd[1]: Stopped MicroShift Containerized.
Mar 26 01:09:50 bruce systemd[1]: Starting MicroShift Containerized...
Mar 26 01:09:51 bruce podman[20234]: Error: statfs /var/run/crio/crio.sock: no such file or directory
Mar 26 01:09:51 bruce systemd[1]: microshift.service: Main process exited, code=exited, status=125/n/a
Mar 26 01:09:51 bruce podman[20270]: Error: error reading CIDFile: open /run/microshift.service.ctr-id: no such file or directory
Mar 26 01:09:51 bruce systemd[1]: microshift.service: Control process exited, code=exited status=125
Mar 26 01:09:51 bruce systemd[1]: microshift.service: Failed with result 'exit-code'.
Mar 26 01:09:51 bruce systemd[1]: Failed to start MicroShift Containerized.

**Comment by mangelajo** [comment]
Seems like cri-o is missing, microshift requires the crio container runtime to be installed and running, was it installed?, is /var/run/crio/crio.sock in place?

I'd check the crio logs

journalctl -u crio

**Comment by thinkahead** [comment]
Works fine for me https://community.ibm.com/community/user/cloud/blogs/alexei-karve/2022/04/24/microshift-14
This issue should be closed if there are no further comments
