### ISSUE TITLE
[BUG] hostpath provisioner “permission denied” on R4E due to SELinux

### ISSUE THREAD

**Issue by DanielFroehlich** [openshift/microshift#643]
#### What happened:
Deployed microshift using RHEL/Edge os-tree. 
Created pvc+pod for the hostpath provisionor that is available from the microshift base installation.
PVC does not get bind, due to PV no created. provisonr pod log shows:

`failed to provision volume with StorageClass "kubevirt-hostpath-provisioner": mkdir /var/hpvolumes/pvc-bb3312ba-ba35-4ca7-8873-b6d8334b22e7: permission denied
` 
I tried
`sudo chmod 777 /var/hpvolumes
`
which did not help. Thats hints to se-linux problems. But
`Installed Packages: microshift-selinux.noarch 4.8.0-2022_03_11_124751.el8
`
is there.
Trying brute force workaround:
`sudo setenforce Permissive
` and restart crio+ushift, and voila, then it works.

[OpenShift Docs have a step to configure SELinux for hostpath provisioning,]( https://docs.openshift.com/container-platform/4.9/virt/virtual_machines/virtual_disks/virt-configuring-local-storage-for-vms.html), maybe the  is missing?

#### What you expected to happen:
should have just worked.

#### How to reproduce it (as minimally and precisely as possible):
see above

#### Environment:
- Microshift version (use `microshift version`):
MicroShift Version: 4.8.0-0.microshift-2022-03-11-124751
Base OKD Version: 4.8.0-0.okd-2021-10-10-030117
- Hardware configuration:
virtualised
- OS (e.g: `cat /etc/os-release`):
NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.5 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"

- Kernel (e.g. `uname -a`):
Linux localhost.localdomain 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Tue Mar 8 12:56:54 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

- Others:
!!! RHEL/Edge rpm-ostree installation!!!

**Comment by DanielFroehlich** [comment]
A much better and less insecure workaround is
`sudo restorecon -R -v /var/hpvolumes
`

**Comment by xsgordon** [comment]
@DanielFroehlich note I am still waiting for your write-up on this.

**Comment by DanielFroehlich** [comment]
TopoLVM provides strict isolation and size enforcement for PVCs, which is usually a good thing, so topolvm should definitely be an option for ushift. 
But is also enforces you you to pre-allocate/configure your PVCs, which can be a problem.

Assume you have 2 PODS, both need local storage, but you dont know upfront which pod is going to need which amount of storage? Or even if the storage demand dynamically changes during runtime? For example, POD A need 100G of storage in the morning but cleans up and shrinks back to 10G at lunch team, but after lunch POD B suddenly needs 80G. If you have only 120G of total storage available and statically assigned to PVCs (using lvm volumes), you would need to constantly monitor and dynamically resize the PVCs. Is shrinking a PVC even  possible with CSI ?

With hostpath, there is no need. You can simply assign all PVCs to the 120G of storage, and it will just work. If a pod consumes all storage, that is a risk of course and can have an impact on other pods. But that can be easily tackled if pods handle "disk full" situations correctly and gracefully (which they should do in any case). That is much easier to implement then a dynamic PVCs resize algorithm.
