### ISSUE TITLE
USHIFT-19: Ship default config file in rpm

### ISSUE THREAD

**Issue by mangelajo** [openshift/microshift#663]
#### What would you like to be added:

Commonly- Linux packaged software includes an example configuration file with the defaults, or optionals
in comments shipped to the etc directory, making customization straight forward during development.

#### Why is this needed:

More common workflow
Easier for developers.

For example I needed several minutes of crawling through documents, while simply looking for the etc
file is the first thing I attempted.

The etc config could contain explanations to the fields, becoming a self-document file.

**Comment by oglok** [comment]
I like this idea. It happened to me when I was working on the service node port range option!

**Comment by ggiguash** [comment]
/retitle USHIFT-19: Ship default config file in rpm
