### ISSUE TITLE
[Enhancement]: Support OKD Console on ARM (Raspberry PI)

### ISSUE THREAD

**Issue by itroyano** [openshift/microshift#682]
Cluster is running with latest git version on my PI 400, with default router pod up as well.

now I've tried to install OKD Console using this doc https://community.ibm.com/community/user/cloud/blogs/alexei-karve/2021/11/23/microshift-1

but the pod created by console deployment, fails with `standard_init_linux.go:228: exec user process caused: exec format error`
presumably, because https://quay.io/repository/openshift/origin-console?tab=tags&tag=latest is an amd64 image and not an arm.

#### What would you like to be added:

A console image that is built for arm64.

**Comment by thinkahead** [comment]
Look at the later blogs in the series for example. Search for "Build and Install the OKD Web Console" in https://community.ibm.com/community/user/cloud/blogs/alexei-karve/2022/03/02/microshift-9 and later blogs

**Comment by dhellmann** [comment]
If the console team produces an ARM build there's no particular reason it shouldn't be able to make it work on MicroShift, but the MicroShift team has no plans to do that work.

**Comment by itroyano** [comment]
> Look at the later blogs in the series for example. Search for "Build and Install the OKD Web Console" in https://community.ibm.com/community/user/cloud/blogs/alexei-karve/2022/03/02/microshift-9 and later blogs

@thinkahead just a quick reminder that you are awesome Sir -
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/83590748/190867539-5ffd1751-b5be-47af-b918-33d91474a5b1.png">

P.S: remove the "podman build & push" part from the Blog to avoid someone overriding your image.
