### ISSUE TITLE
[Enhancement]: Is there resource optimization guideline for other parts of the platform

### ISSUE THREAD

**Issue by huang195** [openshift/microshift#693]
This is more of a question than a feature request. As far as I understand, Microshift tries to minimize resource usage of the control plane components so it can be a better fit for resource constrained devices. However, Microshift cannot be used by itself -- you would need a network plugin, e.g., Flannel, and you would also need other plugins such as various device plugins, to get the platform operational. Even if Microshift is heavily optimized, if users are not careful, the various plugins that they deploy could push the resource utilization back up. So I'm wondering:

1. Is there a way for users to pick and choose which plugins is better optimized for resource constrained environments?
2. For plugin developers, is there a general guide line that they can learn from Microshift developers on how to further reduce their resource footprint?

**Comment by dhellmann** [comment]
Our plan is to provide a set of default choices for CSI, CNI, etc. that let us work with code from components that are commonly used in other OpenShift configurations. We will optimize them to provide a baseline, and then user workloads will run on top. Those drivers are now being tested in the main branch, and there is ongoing work to continue optimizing their configuration further. We do not plan, at this time, to support alternative configurations.
