### ISSUE TITLE
[BUG] Multus fails due to Microshift mis-identifying as Openshift

### ISSUE THREAD

**Issue by usrbinkat** [openshift/microshift#712]
#### What happened:
Microshift mis-identified itself as being Openshift to an operator which changes behavior based on whether it is on a normal Kubernetes distribution, or otherwise if it detects Openshift as the host platform.

In the case of Multus, this results in an otherwise working multus deployment which succeeds in other common scenarios on and off of Openshift failing only on Microshift.

Currently I have been unable to identify the correct path to root causing this issue while debugging on microshift.

#### What you expected to happen:
Expect either vanilla [upstream multus](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/quickstart.md), or [kubevirt/cluster-network-addons-operator](https://github.com/kubevirt/cluster-network-addons-operator) installed multus known to work normally in openshift and non-openshift kubernetes clusters to also work on microshift. 

#### How to reproduce it:

1. [Gist of Microshift + Multus failure scenario with basic pod](https://gist.github.com/usrbinkat/0f08e0600f9a9ff64bf46d1ec9251f23)
2. [Gist of Kubevirt + Multus on microshift failure scenarios](https://gist.github.com/usrbinkat/500a2d7314d938f6582f36059a7c1b29)

#### Environment:
- Microshift version:
  ```
  MicroShift Version: 4.8.0-0.microshift-2022-04-20-141053
  Base OKD Version: 4.8.0-0.okd-2021-10-10-030117
  ```
- Hardware configuration:
  ```
  Bare metal & nested virtualization enabled Fedora 35 OS
  Known to work on identical host and or virtual instances via other kubernetes distributions instead of microshift
  ```
- OS:
  ```
  [kc2user@fedora-microshift ~]$ cat /etc/os-release 
  NAME="Fedora Linux"
  VERSION="35 (Cloud Edition)"
  ID=fedora
  VERSION_ID=35
  VERSION_CODENAME=""
  PLATFORM_ID="platform:f35"
  PRETTY_NAME="Fedora Linux 35 (Cloud Edition)"
  .. truncated ..
  VARIANT="Cloud Edition"
  VARIANT_ID=cloud
  ```
- Kernel:
  ```
  Linux fedora-microshift 5.17.11-200.fc35.x86_64 #1 SMP PREEMPT Wed May 25 14:56:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
  ```

#### Relevant Logs 
```
OpenShift cluster network configuration resource has not been found: no matches for kind "Network" in version "operator.openshift.io/v1"
```
Additional [logs collected](https://termbin.com/imkc) with:
```
k logs -n cluster-network-addons cluster-network-addons-operator-dc8d5d95c-b2bd6 -c cluster-network-addons-operator
```

**Comment by dhellmann** [comment]
I don't think we plan to support Multus, but if someone else wanted to try to make that work it would be possible to change the operator to detect MicroShift using the instructions in https://github.com/openshift/microshift/blob/main/docs/debugging_tips.md
