### ISSUE TITLE
[Enhancement]: Enable AdmisionPlugins

### ISSUE THREAD

**Issue by cmwylie19** [openshift/microshift#713]
#### Design Document Link

PR: #--

#### What would you like to be added:
Enable admission controllers in MicroShift all in one.

#### Why is this needed:
This is needed to simulate OpenShift's Admission Controllers.  We are working with applications that are meant to be deployed on OpenShift. 

When we deploy an app that is destined to run in an OpenShift environment, and it runs in a MicroShift environment, we can be somewhat sure that it will likely run in OpenShift if it runs in MicroShift.

#### Attempts so far
- Using a custom written admisson webhook using `MutatingWebhookConfiguration`
- Enabling `--enable-admission-plugins=NodeRestriction,PodSecurityPolicy` on `kube-apiserver`

Maybe the next attempt is the opa sidecar with `kube-mgmt`

**Comment by dhellmann** [comment]
This should be done in the main branch now.

**Comment by cmwylie19** [comment]
Thank you @dhellmann
