### ISSUE TITLE
Building image from rhel and rhocp channels throws mismatch files from same packages on both channels

### ISSUE THREAD

**Issue by rgordill** [openshift/microshift#800]
#### What happened:

Using 

However, when building an image with osbuild, it throws errors related with same file in different channels, like:

```
Jul 26 07:15:21 rhel86 osbuild-worker[1902]: time="2022-07-26T07:15:21-04:00" level=info msg="    \tfile /etc/issue conflicts between attempted installs of redhat-release-coreos-410.84-2.el8.x86_64 and redhat-release-8.6-0.1.el8.x86_64" jobId=7f0d533b-e351-40bc-91a2-301c2f51d3e9
Jul 26 07:15:21 rhel86 osbuild-worker[1902]: time="2022-07-26T07:15:21-04:00" level=info msg="    \tfile /etc/issue.net conflicts between attempted installs of redhat-release-coreos-410.84-2.el8.x86_64 and redhat-release-8.6-0.1.el8.x86_64" jobId=7f0d533b-e351-40bc-91a2-301c2f51d3e9
Jul 26 07:15:21 rhel86 osbuild-worker[1902]: time="2022-07-26T07:15:21-04:00" level=info msg="    \tfile /etc/os-release conflicts between attempted installs of redhat-release-coreos-410.84-2.el8.x86_64 and redhat-release-8.6-0.1.el8.x86_64" jobId=7f0d533b-e351-40bc-91a2-301c2f51d3e9
...
```
#### What you expected to happen:

Include only packages from rhel channels.

#### How to reproduce it (as minimally and precisely as possible):

1. Create a RHEL image with the notes
2. Run osbuid

#### Environment:
- Microshift version (use `microshift version`): N/A
- Hardware configuration: KVM virtual machine
- OS (e.g: `cat /etc/os-release`):Red Hat Enterprise Linux release 8.6 (Ootpa)
- Kernel (e.g. `uname -a`): Linux rhel86 4.18.0-372.9.1.el8.x86_64 #1 SMP Fri Apr 15 22:12:19 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by rgordill** [comment]
I am using https://github.com/openshift/microshift/blob/main/docs/devenv_rhel8.md, but building it with osbuild-composer.

It is related with dependencies for cri-o on the rhocp channel.

![Screenshot from 2022-07-26 15-32-08](https://user-images.githubusercontent.com/21176597/181019155-93afc4f7-5750-41b9-b831-bc69dafa3d1c.png)

**Comment by rgordill** [comment]
It seems adding redhat-release solve the issue. Also, check https://access.redhat.com/solutions/6964106.

**Comment by dhellmann** [comment]
Thanks for posting the extra details, and I'm glad you have it working!
