### ISSUE TITLE
[BUG] ingress router crashes permanently

### ISSUE THREAD

**Issue by rbaumgar** [openshift/microshift#827]
#### What happened:
Now I have a raspberry 4 with 4GB.
Installed Fedora IOT 36
Installed cri-o 1.23
Microshift nightly build
see #817 

now the ingress router pod crashes.

```
# oc get pod -n openshift-ingress 
NAME                              READY   STATUS             RESTARTS   AGE
router-default-85bcfdd948-8fjpq   0/1     CrashLoopBackOff   17         54m
# oc logs router-default-85bcfdd948-8fjpq -n openshift-ingress
I0802 15:39:57.779938       1 template.go:437] router "msg"="starting router"  "version"="majorFromGit: \nminorFromGit: \ncommitFromGit: 9c9f9f42\nversionFromGit: 4.0.0-312-g9c9f9f42\ngitTreeState: clean\nbuildDate: 2021-10-18T17:15:38Z\n"
I0802 15:39:57.784838       1 metrics.go:155] metrics "msg"="router health and metrics port listening on HTTP and HTTPS"  "address"="0.0.0.0:1936"
I0802 15:39:57.801329       1 router.go:191] template "msg"="creating a new template router"  "writeDir"="/var/lib/haproxy"
I0802 15:39:57.801509       1 router.go:270] template "msg"="router will coalesce reloads within an interval of each other"  "interval"="5s"
I0802 15:39:57.803763       1 router.go:332] template "msg"="watching for changes"  "path"="/etc/pki/tls/private"
I0802 15:39:57.804001       1 router.go:262] router "msg"="router is including routes in all namespaces"  
E0802 15:39:57.923164       1 haproxy.go:418] can't scrape HAProxy: dial unix /var/lib/haproxy/run/haproxy.sock: connect: no such file or directory
I0802 15:39:58.024244       1 router.go:579] template "msg"="router reloaded"  "output"=" - Checking http://localhost:80 ...\n - Health check ok : 0 retry attempt(s).\n"
I0802 15:40:11.630877       1 router.go:579] template "msg"="router reloaded"  "output"=" - Checking http://localhost:80 ...\n - Health check ok : 0 retry attempt(s).\n"
I0802 15:41:26.818298       1 template.go:704] router "msg"="Shutdown requested, waiting 45s for new connections to cease" 
``` 

#### What you expected to happen:

ingress should run permanently.

#### How to reproduce it (as minimally and precisely as possible):

1. '...'
2. '...'

#### Environment:
- Microshift version (use `microshift version`):
MicroShift Version: 4.8.0-0.microshift-unknown
Base OKD Version: 4.8.0-0.okd-2021-10-10-030117

- Hardware configuration: raspberry pi4 4GB
- OS (e.g: `cat /etc/os-release`):
Fedora IOT 36
- Kernel (e.g. `uname -a`):
Linux microshift 5.18.5-200.fc36.aarch64 #1 SMP PREEMPT_DYNAMIC Thu Jun 16 14:28:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

- Others:

**Comment by thinkahead** [comment]
Make sure that you have 
1. opened the ports and CIDR using the firewall-cmd as shown in https://community.ibm.com/community/user/cloud/blogs/alexei-karve/2022/06/20/microshift-21
2. Added your hostname with correct ip address to /etc/hosts
3. Run the [hack/cleanup.sh](https://github.com/thinkahead/microshift/blob/main/hack/cleanup.sh) and start the microshift service again

**Comment by rbaumgar** [comment]
oh shit, I had a typo in the /etc/hosts... sorry
