### ISSUE TITLE
[BUG] sudo subscription-manager repos --enable rhocp-4.10-for-rhel-8-$(uname -i)-rpms

### ISSUE THREAD

**Issue by doyoungim999** [openshift/microshift#837]
#### What happened:
From the link: https://github.com/openshift/microshift/blob/main/docs/devenv_rhel8.md, 
$sudo subscription-manager repos --enable rhocp-4.10-for-rhel-8-$(uname -i)-rpms

The error happened:  
Error: 'rhocp-4.10-for-rhel-8-x86_64-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.

#### What you expected to happen:
No error 
#### How to reproduce it (as minimally and precisely as possible):

1. $sudo subscription-manager repos --enable rhocp-4.10-for-rhel-8-x86_64-rpms

#### Environment:
- Microshift version (use `microshift version`): 
_MicroShift Version: 4.10.0-0.microshift-unknown
Base OCP Version: 4.10.18_
- Hardware configuration:
Intel Notebook 
- OS (e.g: `cat /etc/os-release`):
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"

- Kernel (e.g. `uname -a`):
$ uname -a
Linux localhost.localdomain 4.18.0-372.19.1.el8_6.x86_64 #1 SMP Mon Jul 18 11:14:02 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

- Others:

**Comment by mangelajo** [comment]
It works for me:

**Comment by dhellmann** [comment]
The team has not been able to reproduce this problem. If you're still having trouble, please reopen the ticket with a comment including the output of `subscription-manager repos --list`
