### ISSUE TITLE
[BUG] Microshift fails to start on Fedora 36 with LUKS encrypted disk

### ISSUE THREAD

**Issue by jiridanek** [openshift/microshift#851]
* reopen of https://github.com/openshift/microshift/issues/629

```
W0810 12:42:19.144863       1 fs.go:588] stat failed on /dev/mapper/luks-63cca6c4-98e1-467a-b8ee-acfac51b19ca with error: no such file or directory
E0810 12:42:19.144874       1 kubelet.go:1389] "Failed to start ContainerManager" err="failed to get rootfs info: failed to get device for dir \"/var/lib/kubelet\": could not find device with major: 0, minor: 34 in cached partitions map"
```

See various other incarnations of this for different kubernetes distro projects

* https://github.com/kubernetes-sigs/kind/blob/main/site/content/docs/user/known-issues.md#failed-to-get-rootfs-info--stat-failed-on-dev
   * https://github.com/kubernetes-sigs/kind/issues/2411

**Comment by dhellmann** [comment]
We're focusing on RHEL support for the moment and the main branch has moved on quite a bit from the 4.8 release branch. You could try compiling the main branch, but it may be a few months before the team returns to focusing on Fedora support.

**Comment by jiridanek** [comment]
@dhellmann does CentOS Stream 8 count? I can reproduce the issue on CentOS Stream

**Comment by dhellmann** [comment]
Are you using a build from the main branch or the 4.8 branch?

**Comment by jiridanek** [comment]
main branch, here is the issue filled https://github.com/openshift/microshift/issues/880
