### ISSUE TITLE
USHIFT-317: Revisit AMQ Broker How-to

### ISSUE THREAD

**Issue by pwright** [openshift/microshift#873]
https://github.com/openshift/microshift/blob/main/docs/howto_amq_broker.md

describes how to deploy AMQ 7.8 using templates.
However, 7.8 is no longer the LTS release, which is now 7.10 and only operator deployments are supported this this new LTS.

Maybe consider a simpler deployment like upstream artemis, eg Skupper.io have an example at:

https://github.com/skupperproject/skupper-example-activemq/blob/main/broker/kubernetes.yaml

cc @andytaylor

**Comment by ggiguash** [comment]
/retitle [Documentation] USHIFT-317: Revisit AMQ Broker How-to

**Comment by DanielFroehlich** [comment]
I suggest we switch to the operator based deployment. AMQ Broker 7.10 docs describe how to deploy the operator using CLI, without OLM. This approach should work with MicroShift. https://access.redhat.com/documentation/en-us/red_hat_amq_broker/7.10/html-single/deploying_amq_broker_on_openshift/index#proc-br-deploying-operator-cli_broker-ocp
To keep it simple, I suggest we simply point to these docs for installation, configruation,etc.

**Comment by ggiguash** [comment]
Closing this issue following @DanielFroehlich 's suggestion.

**Comment by ggiguash** [comment]
Closing this issue following @DanielFroehlich 's suggestion.
/close
