### ISSUE TITLE
[BUG] can not start microshift in fedora 36

### ISSUE THREAD

**Issue by TUT-jiayou** [openshift/microshift#908]
#### What happened?
*  I am not sure that is bug.
* I follow the [doc](https://microshift.io/docs/getting-started/) to install and start microshift service. 
* I got the content(No resources found) , type the content (oc get pads -A)
* I try to check the microshift service, get the content
```
journalctl -u microshift
``` 
![image](https://user-images.githubusercontent.com/21277368/187608641-1e26d76e-1b0c-4fbe-b342-f504b1b0c4e7.png)

#### How to reproduce it (as minimally and precisely as possible)?
1. '...'
2. '...'

#### Environment
- MicroShift version (use `microshift version`):
- 4.8
![image](https://user-images.githubusercontent.com/21277368/187609008-890a5a27-f59c-4ced-b39c-0b1816b92d59.png)

- Hardware configuration:
vmware x86-64
- OS (e.g: `cat /etc/os-release`):
- 
![image](https://user-images.githubusercontent.com/21277368/187608782-fed72b98-d791-41fb-a7bc-4486af36fe7b.png)

- Kernel (e.g. `uname -a`):
- 
![image](https://user-images.githubusercontent.com/21277368/187608812-5712539f-159d-425c-8d75-c155e2d7dd89.png)

- Others:

**Comment by TUT-jiayou** [comment]
Hi,all
* I also stop the systemd service and start shell command manual.
```
sudo systemctl disable microshift
sudo systemctl stop microshift
sudo microshift run --roles=controlplane,node
```
* I also get more completed error log.
```
链接：https://pan.baidu.com/s/1OFfdsQRrc65W-oPkkRNPrQ?pwd=gaij 
提取码：gaij 

```

**Comment by ggiguash** [comment]
@TUT-jiayou, thank you for submitting this issue. The latest community version of MicroShift is somewhat behind the latest sources and documentation at https://github.com/openshift/microshift.
Can you try working with the latest version?

**Comment by mangelajo** [comment]
Try using the fedora 35 repo instead of the (change the $releasever to 35) in the /etc/yum/repos.d/ file

The fedora 36 version was building with the wrong golang compiler



[copr:copr.fedorainfracloud.org:group_redhat-et:microshift]
name=Copr repo for microshift owned by @redhat-et
baseurl=https://download.copr.fedorainfracloud.org/results/@redhat-et/microshift/fedora-**$releasever**-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://download.copr.fedorainfracloud.org/results/@redhat-et/microshift/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1

**Comment by TUT-jiayou** [comment]
@mangelajo Thanks. I can run microshift successfully in my fedora 36.
* when I add microshift copr repo, I change the file `/etc/yum.repos.d/_copr\:copr.fedorainfracloud.org\:group_redhat-et\:microshift.repo`
* The file content is below. 
```
[copr:copr.fedorainfracloud.org:group_redhat-et:microshift]
name=Copr repo for microshift owned by @redhat-et
baseurl=https://download.copr.fedorainfracloud.org/results/@redhat-et/microshift/fedora-35-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://download.copr.fedorainfracloud.org/results/@redhat-et/microshift/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
```

* The fedora will be not supported about microshift ?

**Comment by ggiguash** [comment]
@TUT-jiayou While we are focused on RHEL 8 support at this time, we certainly plan to extend it to Fedora and CentOS operating systems in the future.

I'm closing this issue for now. Glad you have it all working on Fedora with the suggested workaround.

/close
